# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af595000b91f56a1920f33f4df4b78564af262ff519a96cb489eb369b9b2c872377d936a106658a9b1c6690da3384da803cef29983546b69f8c999b362895f6

test:
  secret_key_base: d8bc27f570fe0124d3dda6a7c1ed22829c462c6cabea5c82c94dfd2cc56ebb2f5fef9508dc34fc48d675cd1cf19324da85e7e6912ef1f4eb35b8597ed3c79994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
